import { existsSync } from "node:fs";
import { build } from "esbuild";
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { publicConfig } from "./public-config.mjs";
const config = JSON.parse(
  await readFile(
    process.env.BOOKING_CONFIG || (existsSync("config/development.local.json") ? "config/development.local.json" : "config/development.example.json"),
    "utf8",
  ),
);
const content = JSON.parse(
  await readFile("config/service-content.json", "utf8"),
);
const functions = JSON.parse(await readFile("infra/functions.json", "utf8"));
const publicData = publicConfig(config, content);
await mkdir("miniprogram/config", { recursive: true });
await writeFile(
  "miniprogram/config/env.ts",
  "// Generated by npm run build from BOOKING_CONFIG; edit config instead.\nexport const ENV = " +
    JSON.stringify(publicData.env, null, 2) +
    ";\n",
);
await writeFile(
  "miniprogram/config/catalog.ts",
  "// Generated by npm run build from config and service-content.json.\nimport type { Service } from '../../shared/types';\nexport const catalog: Service[] = " +
    JSON.stringify(publicData.catalog, null, 2) +
    ";\nexport const descriptions: Record<string, {intro: string; note: string; tag: string; number: string}> = " +
    JSON.stringify(publicData.descriptions, null, 2) +
    ";\n",
);
const app = JSON.parse(await readFile("miniprogram/app.json", "utf8"));
app.window.navigationBarTitleText = publicData.env.storeName;
await writeFile("miniprogram/app.json", JSON.stringify(app, null, 2) + "\n");
const project = JSON.parse(await readFile(existsSync("project.config.json") ? "project.config.json" : "project.config.example.json", "utf8"));
project.appid = config.appId;
project.setting.useCompilerPlugins = [];
await writeFile("project.config.json", JSON.stringify(project, null, 2) + "\n");
const entries = [];
async function walk(dir) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = `${dir}/${e.name}`;
    if (e.isDirectory()) await walk(p);
    else if (p.endsWith(".ts")) entries.push(p);
  }
}
await walk("miniprogram");
await build({
  entryPoints: entries,
  outbase: "miniprogram",
  outdir: "miniprogram",
  platform: "neutral",
  format: "cjs",
  target: "es2017",
  bundle: false,
  logLevel: "warning",
});
for (const [name, definition] of Object.entries(functions)) {
  const { entry, timeout } = definition;
  await mkdir(`cloudfunctions/${name}`, { recursive: true });
  await build({
    entryPoints: [entry],
    outfile: `cloudfunctions/${name}/index.js`,
    bundle: true,
    platform: "node",
    target: "node20",
    external: ["wx-server-sdk", "@cloudbase/node-sdk"],
    logLevel: "warning",
  });
  await writeFile(
    `cloudfunctions/${name}/package.json`,
    JSON.stringify(
      {
        name,
        version: "1.0.0",
        main: "index.js",
        dependencies: {
          "wx-server-sdk": "4.0.2",
          "@cloudbase/node-sdk": "3.18.3",
        },
        overrides: { "axios@<1": "0.33.0" },
      },
      null,
      2,
    ),
  );
  await writeFile(
    `cloudfunctions/${name}/config.json`,
    JSON.stringify({ permissions: { openapi: [] }, timeout }, null, 2),
  );
}
console.log("小程序及云函数构建完成");
